# Flight Modes
AUTO = "AUTO"
GUIDED="GUIDED"
RTL = "RTL"
LAND = "LAND"
# MavLink Messaging
MISSION_REQUEST = "MISSION_REQUEST"
COMMAND_ACK = "COMMAND_ACK"
MISSION_ACK = "MISSION_ACK"
MAV_RESULT = "MAV_RESULT"
